# Configuration Options
title: Insert Title
author: "Martin Susanto"
theme: tactile

header-pages:
  - design.html
  - documentation.html
  - resources.html


# Github Pages settings that cannot be changed
# lsi: false
# safe: true
# source: https://github.com/LawrenceNel/FA23-E155-A-MAZE-ing-Game-Project.git
# incremental: false
# highlighter: rouge
# gist:
#   noscript: false
# kramdown:
#   math_engine: mathjax
#   syntax_highlighter: rouge
